export const API = {
  auth: {
    login: "/auth/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    me: "/auth/me",
    forgotPassword: "/auth/forgot-password",
    verifyOtp: "/auth/verify-otp",
    resetPassword: "/auth/reset-password",
  },
  employees: {
    list: "/employees",
    me: "/employees/me",
    byEmployeeId: (employeeId: string) => `/employees/by-employee-id/${employeeId}`,
    byId: (id: string) => `/employees/${id}`,
    accountStatus: (id: string) => `/employees/${id}/status`,
    employmentStatus: (id: string) => `/employees/${id}/employment-status`,
    importCsv: "/employees/import-csv",
  },
  attendance: {
    checkIn: "/attendance/check-in",
    checkOut: "/attendance/check-out",
    manual: "/attendance/manual",
    startBreak: "/attendance/start-break",
    endBreak: "/attendance/end-break",
    today: "/attendance/today",
    history: "/attendance/history",
    monthly: "/attendance/monthly",
    corrections: "/attendance/corrections",
    correctionsDirect: "/attendance/corrections/direct",
    correctionsApprove: (id: string) => `/attendance/corrections/${id}/approve`,
    correctionsReject: (id: string) => `/attendance/corrections/${id}/reject`,
  },
  leaves: {
    balance: "/leaves/balance",
    list: "/leaves",
    apply: "/leaves/apply",
    cancel: (id: string) => `/leaves/${id}/cancel`,
    approve: (id: string) => `/leaves/${id}/approve`,
    reject: (id: string) => `/leaves/${id}/reject`,
  },
  org: {
    offices: "/org/offices",
    office: (id: string) => `/org/offices/${id}`,
    departments: "/org/departments",
    department: (id: string) => `/org/departments/${id}`,
    designations: "/org/designations",
    designation: (id: string) => `/org/designations/${id}`,
    teams: "/org/teams",
    team: (id: string) => `/org/teams/${id}`,
    shifts: "/org/shifts",
    shift: (id: string) => `/org/shifts/${id}`,
    holidays: "/org/holidays",
    holiday: (id: string) => `/org/holidays/${id}`,
  },
  dashboard: {
    overview: "/dashboard/overview",
    trend: "/dashboard/trend",
    officeStats: "/dashboard/office-stats",
    recentCheckIns: "/dashboard/recent-check-ins",
  },
  reports: {
    attendance: "/reports/attendance",
    late: "/reports/late",
    absent: "/reports/absent",
    monthly: "/reports/monthly",
    leave: "/reports/leave",
    overtime: "/reports/overtime",
  },
  notifications: {
    list: "/notifications",
    unreadCount: "/notifications/unread-count",
    markRead: (id: string) => `/notifications/${id}/read`,
    markAllRead: "/notifications/read-all",
    registerDeviceToken: "/notifications/device-token",
    revokeDeviceToken: "/notifications/device-token",
  },
  rbac: {
    permissions: "/rbac/permissions",
    roles: "/rbac/roles",
    rolePermissions: (role: string) => `/rbac/roles/${role}/permissions`,
  },
  announcements: {
    list: "/announcements",
    byId: (id: string) => `/announcements/${id}`,
  },
  app: {
    version: "/app/version",
  },
} as const;