export const API = {
  auth: {
    login: "/auth/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    me: "/auth/me",
    forgotPassword: "/auth/forgot-password",
    verifyOtp: "/auth/verify-otp",
    resetPassword: "/auth/reset-password",
  },
  employees: {
    list: "/employees",
    me: "/employees/me",
    byEmployeeId: (employeeId: string) => `/employees/by-employee-id/${employeeId}`,
    byId: (id: string) => `/employees/${id}`,
    accountStatus: (id: string) => `/employees/${id}/status`,
    employmentStatus: (id: string) => `/employees/${id}/employment-status`,
    importCsv: "/employees/import-csv",
  },
  attendance: {
    checkIn: "/attendance/check-in",
    checkOut: "/attendance/check-out",
    manual: "/attendance/manual",
    startBreak: "/attendance/start-break",
    endBreak: "/attendance/end-break",
    today: "/attendance/today",
    history: "/attendance/history",
    monthly: "/attendance/monthly",
    corrections: "/attendance/corrections",
    correctionsDirect: "/attendance/corrections/direct",
    correctionsApprove: (id: string) => `/attendance/corrections/${id}/approve`,
    correctionsReject: (id: string) => `/attendance/corrections/${id}/reject`,
  },
  leaves: {
    balance: "/leaves/balance",
    list: "/leaves",
    apply: "/leaves/apply",
    cancel: (id: string) => `/leaves/${id}/cancel`,
    approve: (id: string) => `/leaves/${id}/approve`,
    reject: (id: string) => `/leaves/${id}/reject`,
  },
  org: {
    offices: "/org/offices",
    office: (id: string) => `/org/offices/${id}`,
    departments: "/org/departments",
    department: (id: string) => `/org/departments/${id}`,
    designations: "/org/designations",
    designation: (id: string) => `/org/designations/${id}`,
    teams: "/org/teams",
    team: (id: string) => `/org/teams/${id}`,
    shifts: "/org/shifts",
    shift: (id: string) => `/org/shifts/${id}`,
    holidays: "/org/holidays",
    holiday: (id: string) => `/org/holidays/${id}`,
  },
  dashboard: {
    overview: "/dashboard/overview",
    trend: "/dashboard/trend",
    officeStats: "/dashboard/office-stats",
    recentCheckIns: "/dashboard/recent-check-ins",
  },
  reports: {
    attendance: "/reports/attendance",
    late: "/reports/late",
    absent: "/reports/absent",
    monthly: "/reports/monthly",
    leave: "/reports/leave",
    overtime: "/reports/overtime",
  },
  notifications: {
    list: "/notifications",
    unreadCount: "/notifications/unread-count",
    markRead: (id: string) => `/notifications/${id}/read`,
    markAllRead: "/notifications/read-all",
    registerDeviceToken: "/notifications/device-token",
    revokeDeviceToken: "/notifications/device-token",
  },
  rbac: {
    permissions: "/rbac/permissions",
    roles: "/rbac/roles",
    rolePermissions: (role: string) => `/rbac/roles/${role}/permissions`,
  },
  announcements: {
    list: "/announcements",
    byId: (id: string) => `/announcements/${id}`,
  },
  documents: {
    upload: "/documents",
    mine: "/documents/my",
    expiring: "/documents/expiring",
    usage: "/documents/usage",
    list: "/documents",
    download: (id: string) => `/documents/${id}/download`,
    delete: (id: string) => `/documents/${id}`,
  },
  policies: {
    mine: "/policies/my",
    acknowledge: (id: string) => `/policies/${id}/acknowledge`,
    list: "/policies",
    report: (id: string) => `/policies/${id}/acknowledgement-report`,
    create: "/policies",
    update: (id: string) => `/policies/${id}`,
    publish: (id: string) => `/policies/${id}/publish`,
    archive: (id: string) => `/policies/${id}/archive`,
    delete: (id: string) => `/policies/${id}`,
  },
  expenses: {
    create: "/expenses",
    list: "/expenses",
    byId: (id: string) => `/expenses/${id}`,
    receipt: (id: string) => `/expenses/${id}/receipt`,
    approve: (id: string) => `/expenses/${id}/approve`,
    reject: (id: string) => `/expenses/${id}/reject`,
    reimburse: (id: string) => `/expenses/${id}/reimburse`,
    withdraw: (id: string) => `/expenses/${id}`,
  },
  payroll: {
    structures: "/payroll/structures",
    structureHistory: (employeeId: string) => `/payroll/structures/${employeeId}/history`,
    runs: "/payroll/runs",
    runById: (id: string) => `/payroll/runs/${id}`,
    approveRun: (id: string) => `/payroll/runs/${id}/approve`,
    deleteRun: (id: string) => `/payroll/runs/${id}`,
    myPayslips: "/payroll/payslips/my",
    payslipById: (id: string) => `/payroll/payslips/${id}`,
    payslipPdf: (id: string) => `/payroll/payslips/${id}/pdf`,
  },
  saas: {
    register: "/saas/register",
    plans: "/saas/plans",
    tenants: "/saas/tenants",
    tenant: (id: string) => `/saas/tenants/${id}`,
    tenantStatus: (id: string) => `/saas/tenants/${id}/status`,
  },
  billing: {
    plans: "/billing/plans",
    entitlements: "/billing/entitlements",
  },
  app: {
    version: "/app/version",
  },
} as const;